export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
}

export const patientConstants = {
    CREATE_PATIENT_REQUEST: 'CREATE_PATIENT_REQUEST',
    CREATE_PATIENT_FAILURE: 'CREATE_PATIENT_FAILURE',
    CREATE_PATIENT_SUCCESS: 'CREATE_PATIENT_SUCCESS',

    CREATE_RELATIVE_REQUEST: 'CREATE_RELATIVE_REQUEST',
    CREATE_RELATIVE_FAILURE: 'CREATE_RELATIVE_FAILURE',
    CREATE_RELATIVE_SUCCESS: 'CREATE_RELATIVE_SUCCESS',

    GET_REQUEST: 'GET_REQUEST',
    GET_FAILURE: 'GET_FAILURE',
    GET_SUCCESS: 'GET_SUCCESS',
}