export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

    UPDATE_PROFILE_PIC_REQUEST: 'UPDATE_PROFILE_PIC_REQUEST',
    UPDATE_PROFILE_PIC_SUCCESS: 'UPDATE_PROFILE_PIC_SUCCESS',
    UPDATE_PROFILE_PIC_FAILURE: 'UPDATE_PROFILE_PIC_FAILURE',
}

export const patientConstants = {
    CREATE_PATIENT_REQUEST: 'CREATE_PATIENT_REQUEST',
    CREATE_PATIENT_FAILURE: 'CREATE_PATIENT_FAILURE',
    CREATE_PATIENT_SUCCESS: 'CREATE_PATIENT_SUCCESS',

    CREATE_RELATIVE_REQUEST: 'CREATE_RELATIVE_REQUEST',
    CREATE_RELATIVE_FAILURE: 'CREATE_RELATIVE_FAILURE',
    CREATE_RELATIVE_SUCCESS: 'CREATE_RELATIVE_SUCCESS',

    GET_REQUEST: 'GET_REQUEST',
    GET_FAILURE: 'GET_FAILURE',
    GET_SUCCESS: 'GET_SUCCESS',

    GET_SEARCH_REQUEST: 'GET_SEARCH_REQUEST',
    GET_SEARCH_FAILURE: 'GET_SEARCH_FAILURE',
    GET_SEARCH_SUCCESS: 'GET_SEARCH_SUCCESS',

    // UPDATE PATIENT
    UPDATE_PATIENT_REQUEST: "UPDATE_PATIENT_REQUEST",
    UPDATE_PATIENT_SUCCESS: "UPDATE_PATIENT_SUCCESS",
    UPDATE_PATIENT_FAILURE: "UPDATE_PATIENT_FAILURE",

    // DELETE PATIENT
    DELETE_PATIENT_REQUEST: "DELETE_PATIENT_REQUEST",
    DELETE_PATIENT_SUCCESS: "DELETE_PATIENT_SUCCESS",
    DELETE_PATIENT_FAILURE: "DELETE_PATIENT_FAILURE",
}

export const consultationConstants = {
    CREATE_CONSULTATION_REQUEST: 'CREATE_CONSULTATION_REQUEST',
    CREATE_CONSULTATION_SUCCESS: 'CREATE_CONSULTATION_SUCCESS',
    CREATE_CONSULTATION_FAILURE: 'CREATE_CONSULTATION_FAILURE',

    GET_ALL_CONSULTATIONS_REQUEST: 'GET_ALL_CONSULTATIONS_REQUEST',
    GET_ALL_CONSULTATIONS_SUCCESS: 'GET_ALL_CONSULTATIONS_SUCCESS',
    GET_ALL_CONSULTATIONS_FAILURE: 'GET_ALL_CONSULTATIONS_FAILURE',

    GET_CONSULTATION_BY_ID_REQUEST: 'GET_CONSULTATION_BY_ID_REQUEST',
    GET_CONSULTATION_BY_ID_SUCCESS: 'GET_CONSULTATION_BY_ID_SUCCESS',
    GET_CONSULTATION_BY_ID_FAILURE: 'GET_CONSULTATION_BY_ID_FAILURE',

    GET_CONSULTATION_BY_PATIENT_ID_REQUEST: 'GET_CONSULTATION_BY_PATIENT_ID_REQUEST',
    GET_CONSULTATION_BY_PATIENT_ID_SUCCESS: 'GET_CONSULTATION_BY_PATIENT_ID_SUCCESS',
    GET_CONSULTATION_BY_PATIENT_ID_FAILURE: 'GET_CONSULTATION_BY_PATIENT_ID_FAILURE',

    UPDATE_CONSULTATION_REQUEST: 'UPDATE_CONSULTATION_REQUEST',
    UPDATE_CONSULTATION_SUCCESS: 'UPDATE_CONSULTATION_SUCCESS',
    UPDATE_CONSULTATION_FAILURE: 'UPDATE_CONSULTATION_FAILURE',

    ADD_ADDITIONAL_FEE_REQUEST: 'ADD_ADDITIONAL_FEE_REQUEST',
    ADD_ADDITIONAL_FEE_SUCCESS: 'ADD_ADDITIONAL_FEE_SUCCESS',
    ADD_ADDITIONAL_FEE_FAILURE: 'ADD_ADDITIONAL_FEE_FAILURE',

    DELETE_CONSULTATION_REQUEST: 'DELETE_CONSULTATION_REQUEST',
    DELETE_CONSULTATION_SUCCESS: 'DELETE_CONSULTATION_SUCCESS',
    DELETE_CONSULTATION_FAILURE: 'DELETE_CONSULTATION_FAILURE',
};

export const patientHistoryConstants = {
    PATIENT_HISTORY_CREATE_REQUEST: "PATIENT_HISTORY_CREATE_REQUEST",
    PATIENT_HISTORY_CREATE_SUCCESS: 'PATIENT_HISTORY_CREATE_SUCCESS',
    PATIENT_HISTORY_CREATE_FAILURE: 'PATIENT_HISTORY_CREATE_FAILURE',
    PATIENT_HISTORY_CREATE_RESET: 'PATIENT_HISTORY_CREATE_RESET',

    PATIENT_HISTORY_GET_REQUEST: 'PATIENT_HISTORY_GET_REQUEST',
    PATIENT_HISTORY_GET_SUCCESS: 'PATIENT_HISTORY_GET_SUCCESS',
    PATIENT_HISTORY_GET_FAILURE: 'PATIENT_HISTORY_GET_FAILURE',

    PATIENT_HISTORY_UPDATE_REQUEST: 'PATIENT_HISTORY_UPDATE_REQUEST',
    PATIENT_HISTORY_UPDATE_SUCCESS: 'PATIENT_HISTORY_UPDATE_SUCCESS',
    PATIENT_HISTORY_UPDATE_FAILURE: 'PATIENT_HISTORY_UPDATE_FAILURE',
    PATIENT_HISTORY_UPDATE_RESET: 'PATIENT_HISTORY_UPDATE_RESET',

    PATIENT_HISTORY_DELETE_REQUEST: 'PATIENT_HISTORY_DELETE_REQUEST',
    PATIENT_HISTORY_DELETE_SUCCESS: 'PATIENT_HISTORY_DELETE_SUCCESS',
    PATIENT_HISTORY_DELETE_FAILURE: 'PATIENT_HISTORY_DELETE_FAILURE',

    PATIENT_HISTORY_LIST_REQUEST: 'PATIENT_HISTORY_LIST_REQUEST',
    PATIENT_HISTORY_LIST_SUCCESS: 'PATIENT_HISTORY_LIST_SUCCESS',
    PATIENT_HISTORY_LIST_FAILURE: 'PATIENT_HISTORY_LIST_FAILURE',
}

export const examinationConstants = {
    CREATE_PATIENT_EXAMINATION_REQUEST: 'CREATE_PATIENT_EXAMINATION_REQUEST',
    CREATE_PATIENT_EXAMINATION_SUCCESS: 'CREATE_PATIENT_EXAMINATION_SUCCESS',
    CREATE_PATIENT_EXAMINATION_FAILURE: 'CREATE_PATIENT_EXAMINATION_FAILURE',

    GET_PATIENT_EXAMINATION_REQUEST: 'GET_PATIENT_EXAMINATION_REQUEST',
    GET_PATIENT_EXAMINATION_SUCCESS: 'GET_PATIENT_EXAMINATION_SUCCESS',
    GET_PATIENT_EXAMINATION_FAILURE: 'GET_PATIENT_EXAMINATION_FAILURE',

    UPDATE_PATIENT_EXAMINATION_REQUEST: 'UPDATE_PATIENT_EXAMINATION_REQUEST',
    UPDATE_PATIENT_EXAMINATION_SUCCESS: 'UPDATE_PATIENT_EXAMINATION_SUCCESS',
    UPDATE_PATIENT_EXAMINATION_FAILURE: 'UPDATE_PATIENT_EXAMINATION_FAILURE',

    // Relative Examination
    CREATE_RELATIVE_EXAMINATION_REQUEST: 'CREATE_RELATIVE_EXAMINATION_REQUEST',
    CREATE_RELATIVE_EXAMINATION_SUCCESS: 'CREATE_RELATIVE_EXAMINATION_SUCCESS',
    CREATE_RELATIVE_EXAMINATION_FAILURE: 'CREATE_RELATIVE_EXAMINATION_FAILURE',

    GET_RELATIVE_EXAMINATION_REQUEST: 'GET_RELATIVE_EXAMINATION_REQUEST',
    GET_RELATIVE_EXAMINATION_SUCCESS: 'GET_RELATIVE_EXAMINATION_SUCCESS',
    GET_RELATIVE_EXAMINATION_FAILURE: 'GET_RELATIVE_EXAMINATION_FAILURE',

    UPDATE_RELATIVE_EXAMINATION_REQUEST: 'UPDATE_RELATIVE_EXAMINATION_REQUEST',
    UPDATE_RELATIVE_EXAMINATION_SUCCESS: 'UPDATE_RELATIVE_EXAMINATION_SUCCESS',
    UPDATE_RELATIVE_EXAMINATION_FAILURE: 'UPDATE_RELATIVE_EXAMINATION_FAILURE',

    CLEAR_EXAMINATION_ERRORS: 'CLEAR_EXAMINATION_ERRORS',
}

export const investigationConstants = {
    CREATE_INVESTIGATION_REQUEST: 'CREATE_INVESTIGATION_REQUEST',
    CREATE_INVESTIGATION_SUCCESS: 'CREATE_INVESTIGATION_SUCCESS',
    CREATE_INVESTIGATION_FAILURE: 'CREATE_INVESTIGATION_FAILURE',

    GET_INVESTIGATION_REQUEST: 'GET_INVESTIGATION_REQUEST',
    GET_INVESTIGATION_SUCCESS: 'GET_INVESTIGATION_SUCCESS',
    GET_INVESTIGATION_FAILURE: 'GET_INVESTIGATION_FAILURE',

    UPDATE_INVESTIGATION_REQUEST: 'UPDATE_INVESTIGATION_REQUEST',
    UPDATE_INVESTIGATION_SUCCESS: 'UPDATE_INVESTIGATION_SUCCESS',
    UPDATE_INVESTIGATION_FAILURE: 'UPDATE_INVESTIGATION_FAILURE',

    CLEAR_INVESTIGATION_ERROR: 'CLEAR_INVESTIGATION_ERROR',

    CREATE_BLOOD_INVESTIGATION_REQUEST: 'CREATE_BLOOD_INVESTIGATION_REQUEST',
    CREATE_BLOOD_INVESTIGATION_SUCCESS: 'CREATE_BLOOD_INVESTIGATION_SUCCESS',
    CREATE_BLOOD_INVESTIGATION_FAILURE: 'CREATE_BLOOD_INVESTIGATION_FAILURE',

    GET_BLOOD_INVESTIGATION_REQUEST: 'GET_BLOOD_INVESTIGATION_REQUEST',
    GET_BLOOD_INVESTIGATION_SUCCESS: 'GET_BLOOD_INVESTIGATION_SUCCESS',
    GET_BLOOD_INVESTIGATION_FAILURE: 'GET_BLOOD_INVESTIGATION_FAILURE',

    UPDATE_BLOOD_INVESTIGATION_REQUEST: 'UPDATE_BLOOD_INVESTIGATION_REQUEST',
    UPDATE_BLOOD_INVESTIGATION_SUCCESS: 'UPDATE_BLOOD_INVESTIGATION_SUCCESS',
    UPDATE_BLOOD_INVESTIGATION_FAILURE: 'UPDATE_BLOOD_INVESTIGATION_FAILURE',

    CLEAR_BLOOD_INVESTIGATION_ERROR: 'CLEAR_BLOOD_INVESTIGATION_ERROR',

    CREATE_GENETIC_INVESTIGATION_REQUEST: 'CREATE_GENETIC_INVESTIGATION_REQUEST',
    CREATE_GENETIC_INVESTIGATION_SUCCESS: 'CREATE_GENETIC_INVESTIGATION_SUCCESS',
    CREATE_GENETIC_INVESTIGATION_FAILURE: 'CREATE_GENETIC_INVESTIGATION_FAILURE',

    GET_GENETIC_INVESTIGATION_REQUEST: 'GET_GENETIC_INVESTIGATION_REQUEST',
    GET_GENETIC_INVESTIGATION_SUCCESS: 'GET_GENETIC_INVESTIGATION_SUCCESS',
    GET_GENETIC_INVESTIGATION_FAILURE: 'GET_GENETIC_INVESTIGATION_FAILURE',

    UPDATE_GENETIC_INVESTIGATION_REQUEST: 'UPDATE_GENETIC_INVESTIGATION_REQUEST',
    UPDATE_GENETIC_INVESTIGATION_SUCCESS: 'UPDATE_GENETIC_INVESTIGATION_SUCCESS',
    UPDATE_GENETIC_INVESTIGATION_FAILURE: 'UPDATE_GENETIC_INVESTIGATION_FAILURE',

    CLEAR_GENETIC_INVESTIGATION_ERROR: 'CLEAR_GENETIC_INVESTIGATION_ERROR',
}