// Options
export const frequencyOptions = [
  { value: "Once Daily", label: "Once Daily" },
  { value: "Twice Daily", label: "Twice Daily" },
  { value: "Thrice Daily", label: "Thrice Daily" },
  { value: "Four Times Daily", label: "Four Times Daily" },
  { value: "Every 4 Hours", label: "Every 4 Hours" },
  { value: "Every 6 Hours", label: "Every 6 Hours" },
  { value: "Every 8 Hours", label: "Every 8 Hours" },
  { value: "Every 12 Hours", label: "Every 12 Hours" },
  { value: "Once Weekly", label: "Once Weekly" },
  { value: "As Needed", label: "As Needed" },
];

export const routeOptions = [
  { value: "Oral", label: "Oral" },
  { value: "Intravenous (IV)", label: "Intravenous (IV)" },
  { value: "Intramuscular (IM)", label: "Intramuscular (IM)" },
  { value: "Subcutaneous (SC)", label: "Subcutaneous (SC)" },
  { value: "Topical", label: "Topical" },
  { value: "Sublingual", label: "Sublingual" },
  { value: "Rectal", label: "Rectal" },
  { value: "Inhalation", label: "Inhalation" },
  { value: "Ophthalmic", label: "Ophthalmic" },
  { value: "Otic", label: "Otic" },
];

// Medicine options list
export const medicineOptions = [
 { value: "1ML SYRING", label: "1ML SYRING" },
{ value: "AIRCROSS DX 100ML", label: "AIRCROSS DX 100ML" },
{ value: "AIRCROSS LS SYRP. 100ML", label: "AIRCROSS LS SYRP. 100ML" },
{ value: "ALKAPAC 100 ML", label: "ALKAPAC 100 ML" },
{ value: "AMYCORDIAL FORTE", label: "AMYCORDIAL FORTE" },
{ value: "ANTI D 150.5ML", label: "ANTI D 150.5ML" },
{ value: "ANTI D 300 1ML", label: "ANTI D 300 1ML" },
{ value: "AQUAGEST 50 INJ.", label: "AQUAGEST 50 INJ." },
{ value: "ARACHITOL-NANO-SUSP", label: "ARACHITOL-NANO-SUSP" },
{ value: "ARGIPROX SUP.", label: "ARGIPROX SUP." },
{ value: "ASOTIC CAP.", label: "ASOTIC CAP." },
{ value: "ATOIMPLANT 6.75MG 0.9ML", label: "ATOIMPLANT 6.75MG 0.9ML" },
{ value: "AUGMENTIN 625MG DUA TAB", label: "AUGMENTIN 625MG DUA TAB" },
{ value: "AUZIFLORA V CAP", label: "AUZIFLORA V CAP" },
{ value: "AZEE 500", label: "AZEE 500" },
{ value: "AZYSAFE-500", label: "AZYSAFE-500" },
{ value: "BEARBILE TAB", label: "BEARBILE TAB" },
{ value: "BELLACLOT INJ.", label: "BELLACLOT INJ." },
{ value: "BELLACLOT MF TAB.", label: "BELLACLOT MF TAB." },
{ value: "BELLAFLAM TAB.", label: "BELLAFLAM TAB." },
{ value: "BELLARISE D SACHET 1GM", label: "BELLARISE D SACHET 1GM" },
{ value: "BELLA WASH", label: "BELLA WASH" },
{ value: "BETNESOL AMPL", label: "BETNESOL AMPL" },
{ value: "BISBERRY", label: "BISBERRY" },
{ value: "BOOSTRIX PFS 0.5ML", label: "BOOSTRIX PFS 0.5ML" },
{ value: "BROGYN-900 DISPO PEN", label: "BROGYN-900 DISPO PEN" },
{ value: "BUSCOGAST 10 MG TAB", label: "BUSCOGAST 10 MG TAB" },
{ value: "BUSCOGAST AMP.", label: "BUSCOGAST AMP." },
{ value: "BYZEPTA TAB.", label: "BYZEPTA TAB." },
{ value: "CABGOLIN 0.5", label: "CABGOLIN 0.5" },
{ value: "CALCIMAX TOTAL", label: "CALCIMAX TOTAL" },
{ value: "CALCINUT-M", label: "CALCINUT-M" },
{ value: "CALPIXEL PLUS", label: "CALPIXEL PLUS" },
{ value: "CALPOL 500 TAB", label: "CALPOL 500 TAB" },
{ value: "CALPOL 650MG", label: "CALPOL 650MG" },
{ value: "CANDID PWD 50GM", label: "CANDID PWD 50GM" },
{ value: "CASIROL.S D3 NANO", label: "CASIROL.S D3 NANO" },
];